//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/Scripts/Gestionnaire/PeripheriqueEntree.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PeripheriqueEntree: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PeripheriqueEntree()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PeripheriqueEntree"",
    ""maps"": [
        {
            ""name"": ""PersoSurSol"",
            ""id"": ""e8f2cf4a-955d-46ac-b08f-ba321243326b"",
            ""actions"": [
                {
                    ""name"": ""Deplacer"",
                    ""type"": ""Value"",
                    ""id"": ""510a788c-0d7f-4833-a9c0-7a76045d2fb0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sauter"",
                    ""type"": ""Button"",
                    ""id"": ""d4a038a0-f8ea-4b20-8f75-a6c77d4a6dfb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Regarder"",
                    ""type"": ""Value"",
                    ""id"": ""30cce859-5e8a-494b-b6b4-a78a7b4dea7e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cliquer"",
                    ""type"": ""Button"",
                    ""id"": ""566b24df-601d-455b-848e-54c983b85411"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""9fcd0035-7d33-43f0-a148-2eb9abb01e16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangementCamera"",
                    ""type"": ""Button"",
                    ""id"": ""b7a0e209-89ce-401d-9d0e-5aab0b68c7ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuTouche"",
                    ""type"": ""Button"",
                    ""id"": ""a0e859ed-585b-4ca6-a109-e3dc1fdba977"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""22bc4d84-413e-425a-b8d9-076c57ae47a6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Deplacer"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d4b57f14-2e83-41a5-a55d-2485a8a2e269"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Deplacer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6e39388c-cec9-4b7e-afc4-595ee88926f6"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Deplacer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""da84da22-0e47-4ffd-898e-6667242addaa"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Deplacer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ecf91392-a354-43aa-b9b0-d1e38e4f2762"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Deplacer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9aa51095-1c19-4b9a-b780-adf03ff734e0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sauter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12114bc9-0a12-4501-8056-9e393d2e2e78"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Regarder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e84ac372-d5c4-4962-a958-7b9ceaf28d29"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cliquer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98eb6e1b-aba4-4525-a02f-658a1e5f1053"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f837f653-b620-4e9c-90fa-3ad3648d0291"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangementCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9519c697-233e-4835-848c-f5f549c1a4b2"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuTouche"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PersoSurSol
        m_PersoSurSol = asset.FindActionMap("PersoSurSol", throwIfNotFound: true);
        m_PersoSurSol_Deplacer = m_PersoSurSol.FindAction("Deplacer", throwIfNotFound: true);
        m_PersoSurSol_Sauter = m_PersoSurSol.FindAction("Sauter", throwIfNotFound: true);
        m_PersoSurSol_Regarder = m_PersoSurSol.FindAction("Regarder", throwIfNotFound: true);
        m_PersoSurSol_Cliquer = m_PersoSurSol.FindAction("Cliquer", throwIfNotFound: true);
        m_PersoSurSol_Sprint = m_PersoSurSol.FindAction("Sprint", throwIfNotFound: true);
        m_PersoSurSol_ChangementCamera = m_PersoSurSol.FindAction("ChangementCamera", throwIfNotFound: true);
        m_PersoSurSol_MenuTouche = m_PersoSurSol.FindAction("MenuTouche", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PersoSurSol
    private readonly InputActionMap m_PersoSurSol;
    private List<IPersoSurSolActions> m_PersoSurSolActionsCallbackInterfaces = new List<IPersoSurSolActions>();
    private readonly InputAction m_PersoSurSol_Deplacer;
    private readonly InputAction m_PersoSurSol_Sauter;
    private readonly InputAction m_PersoSurSol_Regarder;
    private readonly InputAction m_PersoSurSol_Cliquer;
    private readonly InputAction m_PersoSurSol_Sprint;
    private readonly InputAction m_PersoSurSol_ChangementCamera;
    private readonly InputAction m_PersoSurSol_MenuTouche;
    public struct PersoSurSolActions
    {
        private @PeripheriqueEntree m_Wrapper;
        public PersoSurSolActions(@PeripheriqueEntree wrapper) { m_Wrapper = wrapper; }
        public InputAction @Deplacer => m_Wrapper.m_PersoSurSol_Deplacer;
        public InputAction @Sauter => m_Wrapper.m_PersoSurSol_Sauter;
        public InputAction @Regarder => m_Wrapper.m_PersoSurSol_Regarder;
        public InputAction @Cliquer => m_Wrapper.m_PersoSurSol_Cliquer;
        public InputAction @Sprint => m_Wrapper.m_PersoSurSol_Sprint;
        public InputAction @ChangementCamera => m_Wrapper.m_PersoSurSol_ChangementCamera;
        public InputAction @MenuTouche => m_Wrapper.m_PersoSurSol_MenuTouche;
        public InputActionMap Get() { return m_Wrapper.m_PersoSurSol; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PersoSurSolActions set) { return set.Get(); }
        public void AddCallbacks(IPersoSurSolActions instance)
        {
            if (instance == null || m_Wrapper.m_PersoSurSolActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PersoSurSolActionsCallbackInterfaces.Add(instance);
            @Deplacer.started += instance.OnDeplacer;
            @Deplacer.performed += instance.OnDeplacer;
            @Deplacer.canceled += instance.OnDeplacer;
            @Sauter.started += instance.OnSauter;
            @Sauter.performed += instance.OnSauter;
            @Sauter.canceled += instance.OnSauter;
            @Regarder.started += instance.OnRegarder;
            @Regarder.performed += instance.OnRegarder;
            @Regarder.canceled += instance.OnRegarder;
            @Cliquer.started += instance.OnCliquer;
            @Cliquer.performed += instance.OnCliquer;
            @Cliquer.canceled += instance.OnCliquer;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @ChangementCamera.started += instance.OnChangementCamera;
            @ChangementCamera.performed += instance.OnChangementCamera;
            @ChangementCamera.canceled += instance.OnChangementCamera;
            @MenuTouche.started += instance.OnMenuTouche;
            @MenuTouche.performed += instance.OnMenuTouche;
            @MenuTouche.canceled += instance.OnMenuTouche;
        }

        private void UnregisterCallbacks(IPersoSurSolActions instance)
        {
            @Deplacer.started -= instance.OnDeplacer;
            @Deplacer.performed -= instance.OnDeplacer;
            @Deplacer.canceled -= instance.OnDeplacer;
            @Sauter.started -= instance.OnSauter;
            @Sauter.performed -= instance.OnSauter;
            @Sauter.canceled -= instance.OnSauter;
            @Regarder.started -= instance.OnRegarder;
            @Regarder.performed -= instance.OnRegarder;
            @Regarder.canceled -= instance.OnRegarder;
            @Cliquer.started -= instance.OnCliquer;
            @Cliquer.performed -= instance.OnCliquer;
            @Cliquer.canceled -= instance.OnCliquer;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @ChangementCamera.started -= instance.OnChangementCamera;
            @ChangementCamera.performed -= instance.OnChangementCamera;
            @ChangementCamera.canceled -= instance.OnChangementCamera;
            @MenuTouche.started -= instance.OnMenuTouche;
            @MenuTouche.performed -= instance.OnMenuTouche;
            @MenuTouche.canceled -= instance.OnMenuTouche;
        }

        public void RemoveCallbacks(IPersoSurSolActions instance)
        {
            if (m_Wrapper.m_PersoSurSolActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPersoSurSolActions instance)
        {
            foreach (var item in m_Wrapper.m_PersoSurSolActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PersoSurSolActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PersoSurSolActions @PersoSurSol => new PersoSurSolActions(this);
    public interface IPersoSurSolActions
    {
        void OnDeplacer(InputAction.CallbackContext context);
        void OnSauter(InputAction.CallbackContext context);
        void OnRegarder(InputAction.CallbackContext context);
        void OnCliquer(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnChangementCamera(InputAction.CallbackContext context);
        void OnMenuTouche(InputAction.CallbackContext context);
    }
}
